### ISSUE TITLE
Debounce Event

### ISSUE THREAD

**Issue by SimonMo88** [akuntal/react-convenience#1]
Hey @akuntal 

In this example:
`<TextArea onChange={debounceEvent(handlerOnChange, 500)} />`

If the component holding your TextArea is rerendered then your debounce will be recreated as the instance of `debounce` created inside the `debounceEvent` function exists inside that scope.

You might want to assign the return function to a method on the parent class component instead. Or to a constant in the parent scope somewhere.

@Fried-Chicken

**Comment by akuntal** [comment]
Thanks for pointing.. I will update it next time.. 👍

**Comment by SimonMo88** [comment]
No problems, anytime!
